version: '3.1'
services:
  db:
    image: postgres:10-alpine
    volumes:
      - ./data/db/init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: dbUser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: Northwind

  adminer:
    image: adminer
    restart: always
    networks: 
      - mynetwork
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: postgres
      ADMINER_DEFAULT_DB_NAME: Northwind
    ports:
      - 8080:8080

networks:
  mynetwork:
volumes:
  myvolume:
